language: csharp
solution: ./FreecraftCore.Serializer.sln
mono: none
sudo: required
dist: trusty
dotnet: 1.0.3

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore FreecraftCore.Serializer.sln -ConfigFile NuGet.config

before_script:
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"